In [94]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [95]:
data=pd.read_csv('zomato.csv',encoding='latin-1')

In [96]:
data

Restaurant ID                           Restaurant Name  Country Code  \
0           6317637                          Le Petit Souffle           162   
1           6304287                          Izakaya Kikufuji           162   
2           6300002                    Heat - Edsa Shangri-La           162   
3           6318506                                      Ooma           162   
4           6314302                               Sambo Kojin           162   
5          18189371                              Din Tai Fung           162   
6           6300781                                Buffet 101           162   
7           6301290                                   Vikings           162   
8           6300010  Spiral - Sofitel Philippine Plaza Manila           162   
9           6314987                                  Locavore           162   
10          6309903                          Silantro Fil-Mex           162   
11          6309455           Mad Mark's Creamery & Good Eats           162   
12          6318433                          Silantro Fil-Mex           162   
13          6310470                                Guevarra's           162   
14          6314605                   Sodam Korean Restaurant           162   
15         18185059                             Cafe Arabelle           162   
16         18182702                  Nonna's Pasta & Pizzeria           162   
17          6318213                                Balay Dako           162   
18         18255654                Hobing Korean Dessert Cafe           162   
19          6308205                   Wildflour Cafe + Bakery           162   
20          6315438                            NIU by Vikings           162   
21          6310406             The Food Hall by Todd English           162   
22          6600681                               Chez Michou            30   
23          6601005                       Cafí© Daniel Briand            30   
24          6600292                  Casa do Biscoito Mineiro            30   
25          6600441                                     Maori            30   
26          6600970                            Pizza íæ Bessa            30   
27          6600379                                Sushi Loko            30   
28          6600214                                   Beirute            30   
29          6601218                                  New Koto            30   
...             ...                                       ...           ...   
9521        6003426                                      Liva           208   
9522        6000549                Meôhur TavacÛ± Recep Usta           208   
9523        6000871                       íˆukuraÛôa SofrasÛ±           208   
9524        6004011                              Gaga Manjero           208   
9525        6000409                                   Cafemiz           208   
9526        6000019                                   Nusr-Et           208   
9527        6001537                                  Kebap 49           208   
9528        6003668                               Timboo Cafe           208   
9529        6001748                  Meôhur í_zí_elik Aspava           208   
9530        6001757                           YÛ±ldÛ±z Aspava           208   
9531        6000747                                 The Bigos           208   
9532        6002025                                MasabaôÛ±           208   
9533        6003879                               Zigana Pide           208   
9534        6004089                               Dí_veroÛôlu           208   
9535        6000921                               Dí_veroÛôlu           208   
9536        6004813                           Pizza ÛÁl Forno           208   
9537        5904116                       J'adore Chocolatier           208   
9538        5901782                                 Starbucks           208   
9539        5902117                                   Va

In [97]:
data.shape

(9551, 21)

In [98]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [99]:
data.drop(columns=['Restaurant ID','Is delivering now','Switch to order menu','Rating color','Rating text'],inplace=True)

In [100]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [101]:
data=data[data['Country Code']==1]

In [102]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [103]:
len(data['City'].value_counts())

43

In [104]:
data=data[data['City'].isin(['New Delhi','Gurgaon','Noida','Faridabad'])]

In [105]:
data.shape

(7922, 16)

In [106]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [107]:
data.drop(columns=['Country Code','Restaurant Name','Address','Locality','Locality Verbose','Currency'],inplace=True)

In [108]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [109]:
data['Has Table booking'].replace({'Yes':1,'No':0},inplace=True)

In [110]:
data['Has Table booking'].value_counts()

0    6876
1    1046
Name: Has Table booking, dtype: int64

In [111]:
data.shape

(7922, 10)

In [112]:
data['Has Online delivery'].replace({'Yes':1,'No':0},inplace=True)

In [113]:
data['Has Online delivery'].value_counts()

0    5609
1    2313
Name: Has Online delivery, dtype: int64

In [114]:
data.shape

(7922, 10)

In [115]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [116]:
data.corr()['Average Cost for two']

Longitude               0.071752
Latitude                0.070993
Average Cost for two    1.000000
Has Table booking       0.642966
Has Online delivery     0.076953
Price range             0.847985
Aggregate rating        0.328440
Votes                   0.299089
Name: Average Cost for two, dtype: float64

In [117]:
data.drop(columns=['Has Online delivery','Price range'],inplace=True)

In [118]:
data.shape

(7922, 8)

In [119]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Aggregate rating', 'Votes'],
      dtype='object')

In [120]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7922 entries, 865 to 9112
Data columns (total 8 columns):
City                    7922 non-null object
Longitude               7922 non-null float64
Latitude                7922 non-null float64
Cuisines                7922 non-null object
Average Cost for two    7922 non-null int64
Has Table booking       7922 non-null int64
Aggregate rating        7922 non-null float64
Votes                   7922 non-null int64
dtypes: float64(3), int64(3), object(2)
memory usage: 557.0+ KB


In [121]:
a=data.groupby('Cuisines')['Average Cost for two'].mean().sort_values(ascending=False).reset_index()

In [122]:
data=data.merge(a, on="Cuisines")

In [123]:
data.drop(columns=['Cuisines'],inplace=True)

In [124]:
data.head()

City  Longitude   Latitude  Average Cost for two_x  Has Table booking  \
0  Faridabad  77.306640  28.490059                     250                  0   
1  New Delhi  77.049525  28.806199                     500                  0   
2  Faridabad  77.304776  28.490157                     500                  0   
3  Faridabad   0.000000   0.000000                     300                  0   
4  Faridabad  77.305698  28.471985                    1200                  1   

   Aggregate rating  Votes  Average Cost for two_y  
0               2.9      4              375.000000  
1               0.0      0              375.000000  
2               2.8     16              594.303797  
3               0.0      0              594.303797  
4               0.0      0              594.303797

In [125]:
data.rename(columns={"Average Cost for two_x":"cost", "Average Cost for two_y":"cuisine"},inplace=True)

In [126]:
y=data.iloc[:,3].values

In [127]:
y

array([ 250,  500,  500, ...,  450, 1000,  450], dtype=int64)

In [147]:
y.shape

(7922,)

In [148]:
X=data.drop(columns=['cost']).iloc[:,:].values

In [149]:
X

array([['Faridabad', 77.3066401, 28.4900591, ..., 2.9, 4, 375.0],
       ['New Delhi', 77.04952508, 28.80619877, ..., 0.0, 0, 375.0],
       ['Faridabad', 77.304776, 28.490156699999996, ..., 2.8, 16,
        594.3037974683544],
       ...,
       ['Noida', 77.3648332, 28.5971027, ..., 3.5, 105, 450.0],
       ['Noida', 77.32321292, 28.567750899999997, ..., 0.0, 0, 1000.0],
       ['Noida', 77.32530809999999, 28.5671503, ..., 2.0, 161, 450.0]],
      dtype=object)

In [150]:
X.shape

(7922, 7)

In [151]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [152]:
X[:,0]=encoder.fit_transform(X[:,0])

In [153]:
X[:,0]

array([0, 2, 0, ..., 3, 3, 3], dtype=object)

In [154]:
X.shape

(7922, 7)

In [155]:
from sklearn.preprocessing import OneHotEncoder
onencoder=OneHotEncoder(categorical_features=[0])

In [156]:
X=onencoder.fit_transform(X).toarray()

C:\Users\Shantanu Shubham\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [157]:
X.shape

(7922, 10)

In [158]:
X[:,0:4]

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [159]:
X=X[:,1:]

In [160]:
X.shape

(7922, 9)

In [161]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [162]:
from sklearn.linear_model import LinearRegression
regressor1= LinearRegression()

In [172]:
regressor1.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [174]:
y_pred=regressor1.predict(X_test)

In [175]:
y_test.shape

(1981,)

In [176]:
y_pred.shape

(1981,)

In [177]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7419248191359219

In [183]:
from sklearn.tree import DecisionTreeRegressor
regressor2=DecisionTreeRegressor()

In [184]:
regressor2.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [185]:
y_pred2=regressor2.predict(X_test)

In [186]:
r2_score(y_test,y_pred2)

0.3782049716284609

In [188]:
regressor1.intercept_

-56.083848821246306

In [189]:
regressor1.coef_

array([ 3.69049361e+01,  2.95797124e+01,  3.94958201e+01,  8.31053707e+00,
       -2.21420026e+01,  4.75606318e+02,  3.28003906e+01,  8.04189246e-02,
        7.78887361e-01])

In [190]:
from sklearn.ensemble import RandomForestRegressor
regressor3=RandomForestRegressor(n_estimators=300)

In [191]:
regressor3.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [192]:
y_pred3=regressor3.predict(X_test)

In [193]:
r2_score(y_test,y_pred3)

0.7650577763973385

In [194]:
from sklearn.svm import SVR
regressor4=SVR()

In [195]:
regressor4.fit(X_train,y_train)

C:\Users\Shantanu Shubham\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [196]:
y_pred4=regressor4.predict(X_test)

In [197]:
r2_score(y_test,y_pred4)

-0.06109418702959113